# Site settings
title: Sebastian Wozny's adventures with technology
email: s.s.wozny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A story of failure and epic win.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arpheno.github.io" # the base hostname & protocol for your site
twitter_username: arpheno
github_username:  arpheno

# Build settings
markdown: kramdown
